In [2]:
import pandas as pd
import numpy as np

In [3]:
import os
print(os.listdir())

['.config', 'Zomato Dataset.csv', 'sample_data']

In [4]:
df = pd.read_csv("Zomato Dataset.csv")
df.shape
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [5]:
df.columns
df.dtypes

ID                              object
Delivery_person_ID              object
Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weather_conditions              object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries            float64
Festival                        object
City                            object
Time_taken (min)                 int64
dtype: object

In [6]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [7]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_summary

                             Missing_Count  Missing_Percentage
ID                                       0            0.000000
Delivery_person_ID                       0            0.000000
Delivery_person_Age                   1854            4.067217
Delivery_person_Ratings               1908            4.185679
Restaurant_latitude                      0            0.000000
Restaurant_longitude                     0            0.000000
Delivery_location_latitude               0            0.000000
Delivery_location_longitude              0            0.000000
Order_Date                               0            0.000000
Time_Orderd                           1731            3.797385
Time_Order_picked                        0            0.000000
Weather_conditions                     616            1.351351
Road_traffic_density                   601            1.318445
Vehicle_condition                        0            0.000000
Type_of_order                            0            0.000000
Type_of_vehicle                          0            0.000000
multiple_deliveries                    993            2.178396
Festival                               228            0.500176
City                                  1200            2.632503
Time_taken (min)                         0            0.000000

In [8]:
missing_summary[missing_summary["Missing_Count"] > 0].sort_values(
    by="Missing_Count",
    ascending=False
)

                         Missing_Count  Missing_Percentage
Delivery_person_Ratings           1908            4.185679
Delivery_person_Age               1854            4.067217
Time_Orderd                       1731            3.797385
City                              1200            2.632503
multiple_deliveries                993            2.178396
Weather_conditions                 616            1.351351
Road_traffic_density               601            1.318445
Festival                           228            0.500176

In [9]:
missing_summary[missing_summary["Missing_Count"] > 0]

                         Missing_Count  Missing_Percentage
Delivery_person_Age               1854            4.067217
Delivery_person_Ratings           1908            4.185679
Time_Orderd                       1731            3.797385
Weather_conditions                 616            1.351351
Road_traffic_density               601            1.318445
multiple_deliveries                993            2.178396
Festival                           228            0.500176
City                              1200            2.632503

In [10]:
missing_summary[missing_summary["Missing_Count"] > 0].to_string()

'                         Missing_Count  Missing_Percentage\nDelivery_person_Age               1854            4.067217\nDelivery_person_Ratings           1908            4.185679\nTime_Orderd                       1731            3.797385\nWeather_conditions                 616            1.351351\nRoad_traffic_density               601            1.318445\nmultiple_deliveries                993            2.178396\nFestival                           228            0.500176\nCity                              1200            2.632503'

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
for column in df.columns:
  print(f"{column} -> {df[column].dtype}")

ID -> object
Delivery_person_ID -> object
Delivery_person_Age -> float64
Delivery_person_Ratings -> float64
Restaurant_latitude -> float64
Restaurant_longitude -> float64
Delivery_location_latitude -> float64
Delivery_location_longitude -> float64
Order_Date -> object
Time_Orderd -> object
Time_Order_picked -> object
Weather_conditions -> object
Road_traffic_density -> object
Vehicle_condition -> int64
Type_of_order -> object
Type_of_vehicle -> object
multiple_deliveries -> float64
Festival -> object
City -> object
Time_taken (min) -> int64

In [13]:
categorical_columns = df.select_dtypes(include="object").columns
print(categorical_columns.tolist())

['ID', 'Delivery_person_ID', 'Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Weather_conditions', 'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle', 'Festival', 'City']

In [14]:
for column in categorical_columns:
  print(f"{column} -> {df[column].nunique()} unique values")

ID -> 45584 unique values
Delivery_person_ID -> 1320 unique values
Order_Date -> 44 unique values
Time_Orderd -> 176 unique values
Time_Order_picked -> 193 unique values
Weather_conditions -> 6 unique values
Road_traffic_density -> 4 unique values
Type_of_order -> 4 unique values
Type_of_vehicle -> 4 unique values
Festival -> 2 unique values
City -> 3 unique values

In [15]:
df["Weather_conditions"].value_counts(dropna=False)

Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
NaN            616
Name: count, dtype: int64

In [16]:
weather_counts = df["Weather_conditions"].value_counts(dropna=False)
weather_counts
print(weather_counts)

Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
NaN            616
Name: count, dtype: int64

In [17]:
df['Road_traffic_density'].value_counts(dropna=False)

Road_traffic_density
Low       15476
Jam       14139
Medium    10945
High       4423
NaN         601
Name: count, dtype: int64

In [18]:
df['City'].value_counts(dropna=False)

City
Metropolitian    34087
Urban            10133
NaN               1200
Semi-Urban         164
Name: count, dtype: int64

In [19]:
for column in categorical_columns:
  print(f"\n====== {column} ======")
  print("unique values:", df[column].nunique(dropna=True))

  if df[column].nunique(dropna=True) <=20:
    print(df[column].value_counts(dropna=False))

====== ID ======
unique values: 45584

====== Delivery_person_ID ======
unique values: 1320

====== Order_Date ======
unique values: 44

====== Time_Orderd ======
unique values: 176

====== Time_Order_picked ======
unique values: 193

====== Weather_conditions ======
unique values: 6
Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
NaN            616
Name: count, dtype: int64

====== Road_traffic_density ======
unique values: 4
Road_traffic_density
Low       15476
Jam       14139
Medium    10945
High       4423
NaN         601
Name: count, dtype: int64

====== Type_of_order ======
unique values: 4
Type_of_order
Snack     11530
Meal      11456
Drinks    11321
Buffet    11277
Name: count, dtype: int64

====== Type_of_vehicle ======
unique values: 4
Type_of_vehicle
motorcycle          26429
scooter             15273
electric_scooter     3814
bicycle                68
Name: count, dtype: int64

====== Festival ======
unique values: 2
Festival
No     44460
Yes      896
NaN      228
Name: count, dtype: int64

====== City ======
unique values: 3
City
Metropolitian    34087
Urban            10133
NaN               1200
Semi-Urban         164
Name: count, dtype: int64

In [20]:
numeric_columns = df.select_dtypes(include="number").columns

for column in numeric_columns:
  print(f"\n===== { column} ======")
  print(df[column].describe())

===== Delivery_person_Age ======
count    43730.000000
mean        29.566911
std          5.815064
min         15.000000
25%         25.000000
50%         30.000000
75%         35.000000
max         50.000000
Name: Delivery_person_Age, dtype: float64

===== Delivery_person_Ratings ======
count    43676.000000
mean         4.633774
std          0.334744
min          1.000000
25%          4.500000
50%          4.700000
75%          4.900000
max          6.000000
Name: Delivery_person_Ratings, dtype: float64

===== Restaurant_latitude ======
count    45584.000000
mean        17.017948
std          8.185674
min        -30.905562
25%         12.933284
50%         18.551440
75%         22.728163
max         30.914057
Name: Restaurant_latitude, dtype: float64

===== Restaurant_longitude ======
count    45584.000000
mean        70.229684
std         22.885575
min        -88.366217
25%         73.170000
50%         75.897963
75%         78.044095
max         88.433452
Name: Restaurant_longitude, dtype: float64

===== Delivery_location_latitude ======
count    45584.000000
mean        17.465480
std          7.335562
min          0.010000
25%         12.988453
50%         18.633934
75%         22.785049
max         31.054057
Name: Delivery_location_latitude, dtype: float64

===== Delivery_location_longitude ======
count    45584.000000
mean        70.844161
std         21.120578
min          0.010000
25%         73.280000
50%         76.002574
75%         78.107044
max         88.563452
Name: Delivery_location_longitude, dtype: float64

===== Vehicle_condition ======
count    45584.000000
mean         1.023385
std          0.839055
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          3.000000
Name: Vehicle_condition, dtype: float64

===== multiple_deliveries ======
count    44591.000000
mean         0.744635
std          0.572510
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: multiple_deliveries, dtype: float64

===== Time_taken (min) ======
count    45584.000000
mean        26.293963
std          9.384298
min         10.000000
25%         19.000000
50%         26.000000
75%         32.000000
max         54.000000
Name: Time_taken (min), dtype: float64

In [21]:
print("Age range: ")
print(df["Delivery_person_Age"].min(), "to", df["Delivery_person_Age"].max())

print("\nRating range: ")
print(df["Delivery_person_Ratings"].min(), "to", df["Delivery_person_Ratings"].max())

print("\nVehicle condition values: ")
print(df["Vehicle_condition"].value_counts(dropna=False))

print("\nDelivery time range: ")
print(df["Time_taken (min)"].min(), "to", df["Time_taken (min)"].max())

Age range:
15.0 to 50.0

Rating range:
1.0 to 6.0

Vehicle condition values:
Vehicle_condition
2    15031
1    15028
0    15005
3      520
Name: count, dtype: int64

Delivery time range:
10 to 54

In [22]:
print("Invalid age record:", ((df["Delivery_person_Age"] < 18) |
      (df["Delivery_person_Age"] > 60)).sum())

print("Invalid rating records:", ((df["Delivery_person_Ratings"] < 1) |
                                  (df["Delivery_person_Ratings"] > 5)).sum())

print("Invalid delivery-time records:", (df["Time_taken (min)"] <= 0).sum())

Invalid age record: 38
Invalid rating records: 53
Invalid delivery-time records: 0

In [23]:
print("Invalid age record:")
print(df.loc[
    (df["Delivery_person_Age"] < 18) |
    (df["Delivery_person_Age"] > 60),
    ["Delivery_person_Age"]
].value_counts())

print("\n Invalid rating records:")
print(df.loc[
    (df['Delivery_person_Ratings'] < 1) |
    (df['Delivery_person_Ratings'] > 5),
    ["Delivery_person_Ratings"]
].value_counts())

Invalid age record:
Delivery_person_Age
15.0                   38
Name: count, dtype: int64

 Invalid rating records:
Delivery_person_Ratings
6.0                        53
Name: count, dtype: int64

In [24]:
print("Rows with age = 15:")
display(df[df["Delivery_person_Age"] == 15])

print("\nRows with rating = 6:")
display(df[df["Delivery_person_Ratings"] == 6])

Rows with age = 15:

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
2378,0x564,JAPRES15DEL03,15.0,1.0,-26.891191,75.802083,26.981191,75.892083,12-03-2022,NaN,17:20,NaN,NaN,3,Meal,motorcycle,0.0,No,Urban,15
2896,0xcd0,INDORES010DEL03,15.0,1.0,22.750040,75.902847,22.810040,75.962847,03-04-2022,NaN,20:30,NaN,NaN,3,Snack,scooter,1.0,No,Metropolitian,29
2942,0x91a,SURRES17DEL03,15.0,1.0,21.149569,72.772697,21.209569,72.832697,21-03-2022,NaN,22:10,NaN,NaN,3,Buffet,bicycle,1.0,No,Metropolitian,20
5893,0x474,CHENRES15DEL03,15.0,1.0,13.026286,80.275235,13.056286,80.305235,11-03-2022,NaN,20:50,NaN,NaN,3,Drinks,bicycle,1.0,No,Metropolitian,25
9147,0x73f,BANGRES05DEL01,15.0,1.0,12.970324,77.645748,13.080324,77.755748,25-03-2022,NaN,23:25,NaN,NaN,3,Buffet,motorcycle,2.0,No,Metropolitian,34
10891,0x1b49,MUMRES14DEL02,15.0,1.0,19.181300,72.836191,19.231300,72.886191,30-03-2022,NaN,20:55,NaN,NaN,3,Buffet,motorcycle,1.0,No,Metropolitian,39
11116,0x40b,SURRES12DEL01,15.0,1.0,-21.183434,-72.814492,21.193434,72.824492,05-03-2022,NaN,11:30,NaN,NaN,3,Meal,scooter,1.0,No,Urban,27
12084,0x523,INDORES03DEL02,15.0,1.0,22.751857,75.866699,22.801857,75.916699,24-03-2022,NaN,21:15,NaN,NaN,3,Buffet,bicycle,0.0,No,Metropolitian,28
15115,0x18b0,RANCHIRES02DEL01,15.0,1.0,0.000000,0.000000,0.070000,0.070000,16-03-2022,NaN,23:55,NaN,NaN,3,Meal,bicycle,1.0,No,Metropolitian,21
15918,0x550,CHENRES08DEL02,15.0,1.0,13.022394,80.242439,13.072394,80.292439,11-03-2022,NaN,18:10,NaN,NaN,3,Snack,bicycle,0.0,No,Metropolitian,17
16075,0x58c,MUMRES02DEL01,15.0,1.0,-19.221315,72.862381,19.231315,72.872381,30-03-2022,NaN,12:05,NaN,NaN,3,Snack,scooter,0.0,No,Metropolitian,23
16453,0xe4c,MYSRES05DEL03,15.0,1.0,12.323978,76.627961,12.413978,76.717961,27-03-2022,NaN,0.833333333,NaN,NaN,3,Meal,electric_scooter,0.0,No,Urban,24
21213,0x3fc,BANGRES16DEL02,15.0,1.0,13.029198,77.570997,13.159198,77.700997,06-03-2022,NaN,17:15,NaN,NaN,3,Drinks,electric_scooter,0.0,No,Metropolitian,28
22282,0x3ed,RANCHIRES09DEL01,15.0,1.0,-23.351058,-85.325731,23.421058,85.395731,27-03-2022,NaN,21:35,NaN,NaN,3,Buffet,electric_scooter,2.0,Yes,Metropolitian,44
23026,0x415,VADRES17DEL01,15.0,1.0,0.000000,0.000000,0.070000,0.070000,29-03-2022,NaN,1,NaN,NaN,3,Snack,scooter,0.0,No,Urban,27
23479,0x616c,SURRES07DEL02,15.0,1.0,21.170798,72.790489,21.220798,72.840489,24-03-2022,NaN,17:30,NaN,NaN,3,Snack,scooter,1.0,No,Metropolitian,32
23635,0x1ea0,BANGRES17DEL02,15.0,1.0,12.972532,77.608179,13.022532,77.658179,21-03-2022,NaN,17:40,NaN,NaN,3,Drinks,bicycle,1.0,No,Metropolitian,23
23655,0x3f7,CHENRES04DEL01,15.0,1.0,-13.029780,-80.208812,13.139780,80.318812,31-03-2022,NaN,22:40,NaN,NaN,3,Snack,electric_scooter,1.0,No,Urban,15
25864,0xbb3,CHENRES15DEL03,15.0,1.0,13.026286,80.275235,13.116286,80.365235,20-03-2022,NaN,22:50,NaN,NaN,3,Drinks,scooter,0.0,No,Metropolitian,27
26624,0x730,INDORES15DEL02,15.0,1.0,22.760072,75.892574,22.840072,75.972574,12-03-2022,NaN,17:35,NaN,NaN,3,Snack,electric_scooter,1.0,No,Metropolitian,27
26908,0x6e0,CHENRES06DEL03,15.0,1.0,13.054347,80.257221,13.114347,80.317221,01-03-2022,NaN,18:20,NaN,NaN,3,Meal,electric_scooter,1.0,No,Urban,21
27109,0x3f2,BANGRES02DEL02,15.0,1.0,12.970221,77.645396,13.050221,77.725396,02-03-2022,NaN,21:45,NaN,NaN,3,Drinks,electric_scooter,0.0,No,Urban,20
27933,0x681,CHENRES07DEL03,15.0,1.0,13.081878,80.248519,13.111878,80.278519,03-04-2022,NaN,21:50,NaN,NaN,3,Buffet,electric_scooter,1.0,No,Metropolitian,27
27994,0x406,PUNERES14DEL01,15.0,1.0,18.516216,73.842527,18.586216,73.912527,27-03-2022,NaN,19:30,NaN,NaN,3,Buffet,scooter,1.0,No,Metropolitian,38
29655,0x137e,MYSRES19DEL02,15.0,1.0,12.334022,76.618203,12.354022,76.638203,01-03-2022,NaN,09:35,NaN,NaN,3,Drinks,scooter,1.0,No,Metropolitian,13
31207,0x32aa,JAPRES11DEL01,15.0,1.0,26.902940,75.793007,26.912940,75.803007,09-03-2022,NaN,10:05,NaN,NaN,3,Snack,electric_scooter,1.0,No,Urban,19
31950,0x4240,PUNERES05DEL02,15.0,1.0,18.543626,73.905101,18.623626,73.985101,08-03-2022,NaN,21:25,NaN,NaN,3,Meal,bicycle,0.0,No,Metropolitian,21
33189,0x622,CHENRES03DEL02,15.0,1.0,-13.091809,80.219104,13.111809,80.239104,03-03-2022,NaN,11:50,NaN,NaN,3,Buffet,scooter,0.0,No,Metropolitian,33
34944,0x85c,COIMBRES17DEL02,15.0,1.0,11.026117,76.944652,11.046117,76.964652,09-03-2022,NaN,09:10,NaN,NaN,3,Snack,scooter,1.0,No,Metropolitian,19
36012,0xdc0,COIMBRES03DEL03,15.0,1.0,11.025083,77.015393,11.085083,77.075393,03-03-2022,NaN,18:55,NaN,NaN,3,Meal,motorcycle,1.0,No,Metropolitian,28
37091,0x451,HYDRES14DEL03,15.0,1.0,-17.426228,-78.407495,17.486228,78.467495,19-03-2022,NaN,19:05,NaN,NaN,3,Buffet,electric_scooter,1.0,No,Urban,30
37667,0x424,PUNERES20DEL02,15.0,1.0,-18.592718,-73.773572,18.672718,73.853572,16-03-2022,NaN,20:25,NaN,NaN,3,Buffet,scooter,1.0,No,Urban,30
39064,0x4a6,COIMBRES07DEL02,15.0,1.0,-10.961850,-76.971082,11.091850,77.101082,02-03-2022,NaN,19:55,NaN,NaN,3,Drinks,electric_scooter,0.0,No,Metropolitian,24
39073,0x1144,MYSRES05DEL01,15.0,1.0,12.323978,76.627961,12.433978,76.737961,29-03-2022,NaN,22:10,NaN,NaN,3,Snack,electric_scooter,0.0,No,Metropolitian,30
40276,0x442,CHENRES16DEL02,15.0,1.0,-13.049645,-80.242268,13.129645,80.322268,08-03-2022,NaN,23:05,NaN,NaN,3,Snack,bicycle,0.0,No,Metropolitian,25
41232,0x49c,COIMBRES14DEL02,15.0,1.0,11.003681,76.975525,11.133681,77.105525,02-04-2022,NaN,23:45,NaN,NaN,3,Meal,scooter,0.0,No,Metropolitian,25
44394,0x2314,VADRES04DEL01,15.0,1.0,0.000000,0.000000,0.070000,0.070000,14-03-2022,NaN,17:40,NaN,NaN,3,Drinks,scooter,0.0,No,Metropolitian,34
44872,0x8d4,CHENRES02DEL02,15.0,1.0,13.086438,80.220672,13.216439,80.350672,18-03-2022,NaN,0.75,NaN,NaN,3,Snack,electric_scooter,1.0,No,Urban,26

Rows with rating = 6:

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
3577,0x46d,BANGRES05DEL01,50.0,6.0,-12.970324,-77.645748,13.010324,77.685748,13-03-2022,NaN,12:30,NaN,NaN,3,Meal,electric_scooter,0.0,No,Urban,25
4705,0x493,HYDRES17DEL01,50.0,6.0,-17.451976,-78.385883,17.561976,78.495883,04-04-2022,NaN,23:20,NaN,NaN,3,Snack,bicycle,0.0,No,Metropolitian,27
5160,0x4f2,JAPRES08DEL01,50.0,6.0,-26.910262,-75.783013,27.020262,75.893013,18-03-2022,NaN,18:50,NaN,NaN,3,Drinks,scooter,1.0,No,Metropolitian,20
5353,0x430,BANGRES19DEL01,50.0,6.0,12.914264,77.678400,13.024264,77.788400,06-04-2022,NaN,20:55,NaN,NaN,3,Meal,electric_scooter,1.0,No,Metropolitian,18
5642,0xbef1,AGRRES13DEL02,50.0,6.0,-27.159795,-78.042990,27.209795,78.092990,13-02-2022,NaN,18:05,NaN,NaN,3,Drinks,scooter,1.0,No,Metropolitian,20
6385,0x427,JAPRES06DEL02,50.0,6.0,26.911927,75.797282,27.041927,75.927282,02-04-2022,NaN,22:10,NaN,NaN,3,Meal,electric_scooter,0.0,No,Urban,20
7022,0x3eb,MYSRES15DEL02,50.0,6.0,-12.352058,-76.606650,12.372058,76.626650,15-03-2022,NaN,0.416666667,NaN,NaN,3,Buffet,scooter,1.0,No,Metropolitian,14
7672,0xd42,VADRES09DEL01,50.0,6.0,0.000000,0.000000,0.010000,0.010000,21-03-2022,NaN,08:35,NaN,NaN,3,Meal,bicycle,1.0,No,Metropolitian,22
9490,0x3f0,BANGRES010DEL01,50.0,6.0,12.933298,77.614293,13.003298,77.684293,12-03-2022,NaN,18:25,NaN,NaN,3,Drinks,scooter,1.0,No,Urban,17
9526,0x3ef,RANCHIRES13DEL01,50.0,6.0,-23.374989,-85.335486,23.444989,85.405486,20-03-2022,NaN,17:55,NaN,NaN,3,Snack,bicycle,1.0,No,Metropolitian,32
10091,0x5b0,MYSRES04DEL01,50.0,6.0,12.308500,76.665808,12.418500,76.775808,18-03-2022,NaN,20:10,NaN,NaN,3,Snack,electric_scooter,1.0,No,Metropolitian,35
10728,0xbffc,DEHRES18DEL02,50.0,6.0,0.000000,0.000000,0.020000,0.020000,13-02-2022,NaN,08:50,NaN,NaN,3,Snack,scooter,0.0,No,Metropolitian,25
12288,0x940,SURRES02DEL02,50.0,6.0,21.186608,72.794136,21.206608,72.814136,01-03-2022,NaN,11:25,NaN,NaN,3,Meal,scooter,1.0,No,Urban,22
13248,0x490,COIMBRES03DEL02,50.0,6.0,11.025083,77.015393,11.105083,77.095393,23-03-2022,NaN,20:50,NaN,NaN,3,Buffet,electric_scooter,1.0,No,Urban,11
13643,0x434,RANCHIRES01DEL02,50.0,6.0,-23.416792,-85.316842,23.466792,85.366842,13-03-2022,NaN,20:40,NaN,NaN,3,Buffet,motorcycle,0.0,No,Metropolitian,28
14097,0x3f6,MYSRES06DEL02,50.0,6.0,12.323994,76.626167,12.373994,76.676167,03-03-2022,NaN,21:25,NaN,NaN,3,Meal,scooter,0.0,No,Urban,15
14898,0x421,CHENRES19DEL01,50.0,6.0,12.986047,80.218114,12.996047,80.228114,17-03-2022,NaN,09:35,NaN,NaN,3,Drinks,bicycle,0.0,No,Metropolitian,12
14935,0x43c,HYDRES14DEL01,50.0,6.0,17.426228,78.407495,17.536228,78.517495,02-04-2022,NaN,22:50,NaN,NaN,3,Meal,motorcycle,1.0,No,Urban,19
16789,0x3fa,RANCHIRES06DEL02,50.0,6.0,23.357804,85.325146,23.377804,85.345146,13-03-2022,NaN,09:05,NaN,NaN,3,Drinks,scooter,1.0,No,Metropolitian,22
17136,0x400,COIMBRES07DEL01,50.0,6.0,10.961850,76.971082,10.971850,76.981082,05-03-2022,NaN,09:15,NaN,NaN,3,Snack,electric_scooter,0.0,No,Urban,14
17699,0x412,CHENRES010DEL01,50.0,6.0,-13.066762,-80.251865,13.076762,80.261865,17-03-2022,NaN,09:15,NaN,NaN,3,Drinks,electric_scooter,1.0,No,Metropolitian,20
18968,0xc363,BHPRES08DEL03,50.0,6.0,23.232537,77.429845,23.322537,77.519845,18-02-2022,NaN,21:25,NaN,NaN,3,Buffet,scooter,1.0,No,Metropolitian,17
19373,0x3fb,INDORES02DEL03,50.0,6.0,-22.651847,-75.881991,22.711847,75.941991,05-03-2022,NaN,19:30,NaN,NaN,3,Drinks,bicycle,0.0,No,Metropolitian,30
20260,0xd0bc,ALHRES01DEL02,50.0,6.0,25.454648,81.834502,25.504648,81.884502,15-02-2022,NaN,21:55,NaN,NaN,3,Snack,motorcycle,1.0,No,Urban,33
21311,0x810,HYDRES06DEL01,50.0,6.0,17.455894,78.375467,17.525894,78.445467,06-04-2022,NaN,17:30,NaN,NaN,3,Drinks,electric_scooter,1.0,No,Metropolitian,35
22407,0xc7d6,ALHRES08DEL03,50.0,6.0,25.450329,81.834279,25.590329,81.974279,16-02-2022,NaN,17:45,NaN,NaN,3,Drinks,scooter,0.0,No,Metropolitian,29
23366,0x1060,BANGRES05DEL03,50.0,6.0,12.970324,77.645748,13.030324,77.705748,09-03-2022,NaN,22:15,NaN,NaN,3,Buffet,electric_scooter,0.0,No,Urban,19
24228,0x420,SURRES13DEL01,50.0,6.0,-21.170096,-72.789122,21.180096,72.799122,15-03-2022,NaN,10:10,NaN,NaN,3,Meal,motorcycle,0.0,No,Metropolitian,17
24909,0xbf34,KNPRES16DEL02,50.0,6.0,26.482581,80.315628,26.612581,80.445628,12-02-2022,NaN,18:30,NaN,NaN,3,Buffet,scooter,1.0,No,Metropolitian,41
25276,0x40c,COIMBRES08DEL03,50.0,6.0,11.001852,76.976268,11.061852,77.036268,01-03-2022,NaN,17:50,NaN,NaN,3,Meal,electric_scooter,0.0,No,Metropolitian,16
26043,0x694,RANCHIRES09DEL02,50.0,6.0,23.351058,85.325731,23.371058,85.345731,21-03-2022,NaN,08:40,NaN,NaN,3,Meal,electric_scooter,0.0,No,Metropolitian,20
27212,0x3f4,COIMBRES20DEL02,50.0,6.0,-10.994136,-76.963303,11.074136,77.043303,06-03-2022,NaN,17:20,NaN,NaN,3,Drinks,electric_scooter,0.0,No,NaN,17
27390,0x3ea,MUMRES20DEL03,50.0,6.0,19.103249,72.846749,19.133249,72.876749,24-03-2022,NaN,23:20,NaN,NaN,3,Meal,electric_scooter,1.0,No,Metropolitian,18
28306,0x3fd,BANGRES13DEL01,50.0,6.0,-12.935662,-77.614130,13.045662,77.724130,06-03-2022,NaN,17:30,NaN,NaN,3,Drinks,electric_scooter,0.0,No,Metropolitian,28
28965,0x404,CHENRES04DEL01,50.0,6.0,-13.029780,-80.208812,13.099780,80.278812,18-03-2022,NaN,23:55,NaN,NaN,3,Meal,electric_scooter,0.0,No,Metropolitian,20
29526,0x480,BANGRES15DEL01,50.0,6.0,-12.975377,-77.696664,13.015377,77.736664,01-03-2022,NaN,13:55,NaN,NaN,3,Drinks,electric_scooter,1.0,No,Metropolitian,15
30570,0xbf12,BHPRES20DEL03,50.0,6.0,23.235123,77.398886,23.325123,77.488886,16-02-2022,NaN,23:10,NaN,NaN,3,Snack,bicycle,2.0,No,Metropolitian,39
30934,0x4cc,MUMRES20DEL01,50.0,6.0,-19.103249,-72.846749,19.213249,72.956749,16-03-2022,NaN,0.916666667,NaN,NaN,3,Meal,scooter,1.0,No,Urban,30
31224,0x706,VADRES09DEL02,50.0,6.0,0.000000,0.000000,0.050000,0.050000,11-03-2022,NaN,22:30,NaN,NaN,3,Drinks,scooter,0.0,No,Metropolitian,28
32317,0xbf33,KNPRES03DEL03,50.0,6.0,-26.469003,-80.316344,26.559003,80.406344,14-02-2022,NaN,22:55,NaN,NaN,3,Drinks,scooter,0.0,No,NaN,17
33524,0xbf01,KOLRES06DEL02,50.0,6.0,-22.533662,-88.366217,22.663662,88.496217,18-02-2022,NaN,21:50,NaN,NaN,3,Snack,scooter,1.0,No,Metropolitian,28
34679,0xbf76,AGRRES20DEL03,50.0,6.0,-27.158822,-78.045359,27.248822,78.135359,14-02-2022,NaN,23:55,NaN,NaN,3,Drinks,electric_scooter,1.0,No,Urban,16
37998,0xbef2,DEHRES13DEL01,50.0,6.0,30.366322,78.070453,30.436322,78.140453,14-02-2022,NaN,18:05,NaN,NaN,3,Snack,electric_scooter,1.0,No,Metropolitian,25
38011,0x466,CHENRES14DEL02,50.0,6.0,13.026279,80.174568,13.106279,80.254568,20-03-2022,NaN,23:10,NaN,NaN,3,Meal,scooter,0.0,No,Metropolitian,14
38552,0x3f1,VADRES09DEL03,50.0,6.0,0.000000,0.000000,0.090000,0.090000,06-04-2022,NaN,19:20,NaN,NaN,3,Drinks,electric_scooter,0.0,No,Metropolitian,36
38640,0x5e0,MUMRES07DEL03,50.0,6.0,-19.091458,72.827808,19.121458,72.857808,11-03-2022,NaN,21:50,NaN,NaN,3,Buffet,electric_scooter,1.0,No,Urban,26
39690,0xa24,RANCHIRES14DEL03,50.0,6.0,0.000000,0.000000,0.030000,0.030000,21-03-2022,NaN,21:10,NaN,NaN,3,Buffet,bicycle,1.0,No,Metropolitian,39
40214,0x3e9,MYSRES04DEL03,50.0,6.0,-12.308500,-76.665808,12.398500,76.755808,12-03-2022,NaN,17:45,NaN,NaN,3,Drinks,electric_scooter,1.0,No,Metropolitian,40
41096,0x4e4,VADRES17DEL01,50.0,6.0,0.000000,0.000000,0.110000,0.110000,20-03-2022,NaN,21:55,NaN,NaN,3,Meal,scooter,1.0,Yes,Metropolitian,48
41960,0xbef4,KNPRES19DEL03,50.0,6.0,-26.490950,-80.318656,26.520950,80.348656,13-02-2022,NaN,1,NaN,NaN,3,Drinks,scooter,1.0,No,Metropolitian,15
42063,0x5fc,INDORES11DEL03,50.0,6.0,22.751234,75.889490,22.781234,75.919490,17-03-2022,NaN,20:40,NaN,NaN,3,Buffet,scooter,0.0,No,Metropolitian,28
42826,0x53e,BANGRES12DEL01,50.0,6.0,-12.939496,77.625999,12.949496,77.635999,19-03-2022,NaN,09:40,NaN,NaN,3,Drinks,electric_scooter,1.0,No,Metropolitian,19
45323,0x2950,VADRES04DEL02,50.0,6.0,0.000000,0.000000,0.020000,0.020000,19-03-2022,NaN,10:40,NaN,NaN,3,Drinks,electric_scooter,1.0,No,Urban,28

In [25]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100).round(2)

})

print(missing_summary[missing_summary["Missing_Count"] > 0])

                         Missing_Count  Missing_Percentage
Delivery_person_Age               1854                4.07
Delivery_person_Ratings           1908                4.19
Time_Orderd                       1731                3.80
Weather_conditions                 616                1.35
Road_traffic_density               601                1.32
multiple_deliveries                993                2.18
Festival                           228                0.50
City                              1200                2.63

In [26]:
print("Missing-value columns:")
for column in missing_summary[missing_summary["Missing_Count"] > 0].index:
  print(f"\n==== {column} =====")
  print(df.loc[df[column].isnull(), column].head())

Missing-value columns:

==== Delivery_person_Age =====
33    NaN
65    NaN
111   NaN
131   NaN
170   NaN
Name: Delivery_person_Age, dtype: float64

==== Delivery_person_Ratings =====
33    NaN
65    NaN
111   NaN
118   NaN
131   NaN
Name: Delivery_person_Ratings, dtype: float64

==== Time_Orderd =====
33     NaN
65     NaN
111    NaN
131    NaN
170    NaN
Name: Time_Orderd, dtype: object

==== Weather_conditions =====
65     NaN
111    NaN
241    NaN
339    NaN
416    NaN
Name: Weather_conditions, dtype: object

==== Road_traffic_density =====
65     NaN
111    NaN
241    NaN
339    NaN
416    NaN
Name: Road_traffic_density, dtype: object

==== multiple_deliveries =====
8     NaN
77    NaN
86    NaN
126   NaN
135   NaN
Name: multiple_deliveries, dtype: float64

==== Festival =====
1392    NaN
1397    NaN
1406    NaN
1577    NaN
1614    NaN
Name: Festival, dtype: object

==== City =====
49     NaN
107    NaN
131    NaN
141    NaN
197    NaN
Name: City, dtype: object

In [27]:
raw_df = df.copy()
clean_df = df.copy()

print("Raw dataset shape:", raw_df.shape)
print("working dataset shape:", clean_df.shape)

Raw dataset shape: (45584, 20)
working dataset shape: (45584, 20)

In [28]:
print("Missing age records:")
print(
    clean_df.loc[
        clean_df["Delivery_person_Age"].isnull(),
        ["Delivery_person_ID", "City", "Delivery_person_Ratings", "Vehicle_condition"]
    ].head(10)
)

Missing age records:
    Delivery_person_ID           City  Delivery_person_Ratings  \
33       MUMRES17DEL02  Metropolitian                      NaN
65      BANGRES13DEL01  Metropolitian                      NaN
111      VADRES06DEL01  Metropolitian                      NaN
131     PUNERES05DEL03            NaN                      NaN
170      JAPRES03DEL01  Metropolitian                      NaN
222   RANCHIRES14DEL01  Metropolitian                      NaN
241     PUNERES16DEL01          Urban                      NaN
251     CHENRES06DEL02          Urban                      NaN
280     PUNERES02DEL03          Urban                      NaN
296   RANCHIRES08DEL01  Metropolitian                      NaN

     Vehicle_condition
33                   1
65                   1
111                  3
131                  2
170                  0
222                  1
241                  3
251                  1
280                  2
296                  2

In [29]:
age_median = clean_df["Delivery_person_Age"].median()

print("Median delivery person age:", age_median)

Median delivery person age: 30.0

In [30]:
clean_df["Delivery_person_Age"] = clean_df["Delivery_person_Age"].fillna(age_median)

print("Missing ages after cleaning:",
      clean_df["Delivery_person_Age"].isnull().sum())

Missing ages after cleaning: 0

In [31]:
print("Missing rating records:")
print(
    clean_df.loc[
        clean_df["Delivery_person_Ratings"].isnull(),
        ["Delivery_person_ID", "Delivery_person_Age", "City", "Vehicle_condition"]
    ].head(10)
)

Missing rating records:
    Delivery_person_ID  Delivery_person_Age           City  Vehicle_condition
33       MUMRES17DEL02                 30.0  Metropolitian                  1
65      BANGRES13DEL01                 30.0  Metropolitian                  1
111      VADRES06DEL01                 30.0  Metropolitian                  3
118      KOLRES17DEL03                 23.0  Metropolitian                  0
131     PUNERES05DEL03                 30.0            NaN                  2
170      JAPRES03DEL01                 30.0  Metropolitian                  0
222   RANCHIRES14DEL01                 30.0  Metropolitian                  1
241     PUNERES16DEL01                 30.0          Urban                  3
251     CHENRES06DEL02                 30.0          Urban                  1
280     PUNERES02DEL03                 30.0          Urban                  2

In [32]:
rating_median = clean_df["Delivery_person_Ratings"].median()

print("Median delivery person rating:", rating_median)

Median delivery person rating: 4.7

In [33]:
clean_df["Delivery_person_Ratings"] = clean_df["Delivery_person_Ratings"].fillna(rating_median)

print(
    "Missing ratings after cleaning:",
    clean_df["Delivery_person_Ratings"].isnull().sum()
)

Missing ratings after cleaning: 0

In [34]:
print("Time_Orderd sample values:")
print(clean_df["Time_Orderd"].dropna().head(20).tolist())

print("\nData type:")
print(clean_df["Time_Orderd"].dtype)

Time_Orderd sample values:
['21:55', '14:55', '17:30', '09:20', '19:50', '20:25', '14:55', '20:30', '20:40', '21:15', '20:20', '22:30', '08:15', '19:30', '12:25', '18:35', '20:35', '23:20', '21:20', '23:35']

Data type:
object

In [35]:
clean_df["Time_Orderd"] = pd.to_datetime(
    clean_df["Time_Orderd"],
    format="%H:%M",
    errors="coerce"
).dt.time

print("Data type after conversion:", clean_df["Time_Orderd"].dtype)
print("Missing Time_Orderd values:", clean_df["Time_Orderd"].isnull().sum())

Data type after conversion: object
Missing Time_Orderd values: 5799

In [36]:
print(clean_df["Weather_conditions"].value_counts(dropna=False))

Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
NaN            616
Name: count, dtype: int64

In [37]:
clean_df["Weather_conditions"] = clean_df["Weather_conditions"].fillna("Unknown")

print(
    "Missing weather values after cleaning:",
    clean_df["Weather_conditions"].isnull().sum()
)

print("\nWeather categories after cleaning:")
print(clean_df["Weather_conditions"].value_counts())

Missing weather values after cleaning: 0

Weather categories after cleaning:
Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
Unknown        616
Name: count, dtype: int64

In [38]:
print(clean_df["Road_traffic_density"].value_counts(dropna=False))

Road_traffic_density
Low       15476
Jam       14139
Medium    10945
High       4423
NaN         601
Name: count, dtype: int64

In [39]:
clean_df["Road_traffic_density"] = clean_df["Road_traffic_density"].fillna("Unknown")

print(
    "Missing traffic values after cleaning:",
    clean_df["Road_traffic_density"].isnull().sum()
)

print("\nTraffic categories after cleaning:")
print(clean_df["Road_traffic_density"].value_counts())

Missing traffic values after cleaning: 0

Traffic categories after cleaning:
Road_traffic_density
Low        15476
Jam        14139
Medium     10945
High        4423
Unknown      601
Name: count, dtype: int64

In [40]:
print(clean_df["multiple_deliveries"].value_counts(dropna=False))

multiple_deliveries
1.0    28151
0.0    14094
2.0     1985
NaN      993
3.0      361
Name: count, dtype: int64

In [41]:
clean_df["multiple_deliveries"] = clean_df["multiple_deliveries"].fillna("Unknown")

print(
    "Missing multiple_deliveries after cleaning:",
    clean_df["multiple_deliveries"].isnull().sum()
)

print("\nValues after cleaning:")
print(clean_df["multiple_deliveries"].value_counts())

Missing multiple_deliveries after cleaning: 0

Values after cleaning:
multiple_deliveries
1.0        28151
0.0        14094
2.0         1985
Unknown      993
3.0          361
Name: count, dtype: int64

In [42]:
print(clean_df["Festival"].value_counts(dropna=False))

Festival
No     44460
Yes      896
NaN      228
Name: count, dtype: int64

In [43]:
clean_df["Festival"] = clean_df["Festival"].fillna("Unknown")

print(
    "Missing Festival values after cleaning:",
    clean_df["Festival"].isnull().sum()
)

print("\nFestival values after cleaning:")
print(clean_df["Festival"].value_counts())

Missing Festival values after cleaning: 0

Festival values after cleaning:
Festival
No         44460
Yes          896
Unknown      228
Name: count, dtype: int64

In [44]:
print(clean_df["City"].value_counts(dropna=False))

City
Metropolitian    34087
Urban            10133
NaN               1200
Semi-Urban         164
Name: count, dtype: int64

In [45]:
clean_df["City"] = clean_df["City"].fillna("Unknown")

print(
    "Missing City values after cleaning:",
    clean_df["City"].isnull().sum()
)

print("\nCity values after cleaning:")
print(clean_df["City"].value_counts())

Missing City values after cleaning: 0

City values after cleaning:
City
Metropolitian    34087
Urban            10133
Unknown           1200
Semi-Urban         164
Name: count, dtype: int64

In [46]:
# Replace invalid age values with missing
clean_df.loc[
    (clean_df["Delivery_person_Age"] < 18) |
    (clean_df["Delivery_person_Age"] > 60),
    "Delivery_person_Age"
] = np.nan

# Replace invalid rating values with missing
clean_df.loc[
    (clean_df["Delivery_person_Ratings"] < 1) |
    (clean_df["Delivery_person_Ratings"] > 5),
    "Delivery_person_Ratings"
] = np.nan

print("Invalid age values remaining:",
      ((clean_df["Delivery_person_Age"] < 18) |
       (clean_df["Delivery_person_Age"] > 60)).sum())

print("Invalid rating values remaining:",
      ((clean_df["Delivery_person_Ratings"] < 1) |
       (clean_df["Delivery_person_Ratings"] > 5)).sum())

Invalid age values remaining: 0
Invalid rating values remaining: 0

In [47]:
# Fill invalid/missing ages with the median
clean_df["Delivery_person_Age"] = clean_df["Delivery_person_Age"].fillna(age_median)

# Fill invalid/missing ratings with the median
clean_df["Delivery_person_Ratings"] = clean_df["Delivery_person_Ratings"].fillna(rating_median)

print("Missing ages remaining:",
      clean_df["Delivery_person_Age"].isnull().sum())

print("Missing ratings remaining:",
      clean_df["Delivery_person_Ratings"].isnull().sum())

Missing ages remaining: 0
Missing ratings remaining: 0

In [48]:
final_missing = pd.DataFrame({
    "Missing_Count": clean_df.isnull().sum(),
    "Missing_Percentage": (
        clean_df.isnull().sum() / len(clean_df) * 100
    ).round(2)
})

print(final_missing[final_missing["Missing_Count"] > 0])

             Missing_Count  Missing_Percentage
Time_Orderd           5799               12.72

In [49]:
# Check the original values
invalid_time_values = raw_df.loc[
    clean_df["Time_Orderd"].isnull() & raw_df["Time_Orderd"].notnull(),
    "Time_Orderd"
]

print("Number of invalid time values:", len(invalid_time_values))
print("\nExamples of invalid values:")
print(invalid_time_values.head(20).to_list())

Number of invalid time values: 4068

Examples of invalid values:
['0.458333333', '0.958333333', '0.791666667', '0.875', '0.958333333', '1', '0.375', '0.791666667', '0.958333333', '0.625', '0.375', '0.833333333', '0.666666667', '0.791666667', '0.75', '0.458333333', '0.458333333', '0.875', '0.416666667', '0.916666667']

In [50]:
print("Original Time_Orderd data types:")
print(raw_df["Time_Orderd"].map(type).value_counts())

print("\nSample of all non-null formats:")
print(raw_df["Time_Orderd"].dropna().head(30).to_list())

Original Time_Orderd data types:
Time_Orderd
<class 'str'>      43853
<class 'float'>     1731
Name: count, dtype: int64

Sample of all non-null formats:
['21:55', '14:55', '17:30', '09:20', '19:50', '20:25', '14:55', '20:30', '20:40', '21:15', '20:20', '22:30', '08:15', '19:30', '12:25', '18:35', '20:35', '23:20', '21:20', '23:35', '22:35', '22:35', '23:25', '13:35', '21:35', '22:35', '18:55', '14:15', '0.458333333', '09:45']

In [53]:
from datetime import datetime, time

def clean_order_time(value):
    if pd.isna(value):
        return None

    value = str(value).strip()

    # Excel fractional time stored as text
    try:
        numeric_value = float(value)

        if 0 <= numeric_value <= 1:
            total_seconds = round(numeric_value * 24 * 60 * 60)

            hours = (total_seconds // 3600) % 24
            minutes = (total_seconds % 3600) // 60

            return time(hours, minutes)
    except ValueError:
        pass

    # Normal HH:MM format
    try:
        return datetime.strptime(value, "%H:%M").time()
    except ValueError:
        return None


clean_df["Time_Orderd"] = raw_df["Time_Orderd"].apply(clean_order_time)

print("Missing Time_Orderd after cleaning:",
      clean_df["Time_Orderd"].isnull().sum())

print("\nSample cleaned values:")
print(clean_df["Time_Orderd"].dropna().head(20).to_list())

Missing Time_Orderd after cleaning: 1731

Sample cleaned values:
[datetime.time(21, 55), datetime.time(14, 55), datetime.time(17, 30), datetime.time(9, 20), datetime.time(19, 50), datetime.time(20, 25), datetime.time(14, 55), datetime.time(20, 30), datetime.time(20, 40), datetime.time(21, 15), datetime.time(20, 20), datetime.time(22, 30), datetime.time(8, 15), datetime.time(19, 30), datetime.time(12, 25), datetime.time(18, 35), datetime.time(20, 35), datetime.time(23, 20), datetime.time(21, 20), datetime.time(23, 35)]

In [54]:
final_missing = pd.DataFrame({
    "Missing_Count": clean_df.isnull().sum(),
    "Missing_Percentage": (
        clean_df.isnull().sum() / len(clean_df) * 100
    ).round(2)
})

print(final_missing[final_missing["Missing_Count"] > 0])

             Missing_Count  Missing_Percentage
Time_Orderd           1731                 3.8

In [55]:
print("Age range:",
      clean_df["Delivery_person_Age"].min(),
      "to",
      clean_df["Delivery_person_Age"].max())

print("Rating range:",
      clean_df["Delivery_person_Ratings"].min(),
      "to",
      clean_df["Delivery_person_Ratings"].max())

print("Delivery time range:",
      clean_df["Time_taken (min)"].min(),
      "to",
      clean_df["Time_taken (min)"].max())

print("\nInvalid ages:",
      ((clean_df["Delivery_person_Age"] < 18) |
       (clean_df["Delivery_person_Age"] > 60)).sum())

print("Invalid ratings:",
      ((clean_df["Delivery_person_Ratings"] < 1) |
       (clean_df["Delivery_person_Ratings"] > 5)).sum())

print("Invalid delivery times:",
      (clean_df["Time_taken (min)"] <= 0).sum())

Age range: 20.0 to 50.0
Rating range: 1.0 to 5.0
Delivery time range: 10 to 54

Invalid ages: 0
Invalid ratings: 0
Invalid delivery times: 0

In [56]:
print("Duplicate rows after cleaning:",
      clean_df.duplicated().sum())

Duplicate rows after cleaning: 0

In [57]:
print("Raw dataset shape:", raw_df.shape)
print("Cleaned dataset shape:", clean_df.shape)

print("\nRows changed:",
      len(raw_df) - len(clean_df))

print("Columns changed:",
      len(raw_df.columns) - len(clean_df.columns))

Raw dataset shape: (45584, 20)
Cleaned dataset shape: (45584, 20)

Rows changed: 0
Columns changed: 0

In [58]:
for column in [
    "Weather_conditions",
    "Road_traffic_density",
    "multiple_deliveries",
    "Festival",
    "City"
]:
    print(column, "Unknown:",
          (clean_df[column] == "Unknown").sum())

Weather_conditions Unknown: 616
Road_traffic_density Unknown: 601
multiple_deliveries Unknown: 993
Festival Unknown: 228
City Unknown: 1200

In [59]:
print("Final dataset preview:")
display(clean_df.head())

print("\nFinal data types:")
print(clean_df.dtypes)

Final dataset preview:

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55:00,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55:00,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30:00,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20:00,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50:00,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

Final data types:
ID                              object
Delivery_person_ID              object
Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weather_conditions              object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries             object
Festival                        object
City                            object
Time_taken (min)                 int64
dtype: object

In [60]:
cleaned_file = "zomato_cleaned_by_manisha.csv"

clean_df.to_csv(cleaned_file, index=False)

print("Cleaned dataset saved successfully as:", cleaned_file)

Cleaned dataset saved successfully as: zomato_cleaned_by_manisha.csv

In [61]:
quality_summary = {
    "Original Rows": len(raw_df),
    "Cleaned Rows": len(clean_df),
    "Original Columns": len(raw_df.columns),
    "Cleaned Columns": len(clean_df.columns),
    "Duplicate Rows Found": raw_df.duplicated().sum(),
    "Duplicate Rows After Cleaning": clean_df.duplicated().sum(),
    "Invalid Ages Fixed": 38,
    "Invalid Ratings Fixed": 53,
    "Remaining Missing Time_Orderd": clean_df["Time_Orderd"].isnull().sum()
}

for key, value in quality_summary.items():
    print(f"{key}: {value}")

Original Rows: 45584
Cleaned Rows: 45584
Original Columns: 20
Cleaned Columns: 20
Duplicate Rows Found: 0
Duplicate Rows After Cleaning: 0
Invalid Ages Fixed: 38
Invalid Ratings Fixed: 53
Remaining Missing Time_Orderd: 1731